### ISSUE TITLE
I have a few questions to ask you

### ISSUE THREAD

**Issue by baijuexzz** [kenwaytis/faster-SadTalker-API#1]
Hello kenwaytis, I have a few questions to ask you.
Where can I obtain the image of ttsServer?
Regarding the face enhancement part, I noticed that you changed the gfpgan model from pth to onnx format. Where can I get the model in this format?
Thank you very much for your open source contribution.

**Comment by kenwaytis** [comment]
@baijuexzz 
Firstly, concerning the location of the TTS server image, I'm pleased to inform you that this has been combined in same docker-compose.yml file in our most recent update. Secondly, with regard to the transition of the gfpgan model from pth to ONNX format, the model in this specific format can now be accessed in our latest releases.

Please refer to the latest README in our repository, where you'll find detailed guidance to rerun the project with the new improvements.

I genuinely appreciate your interest in our work, and I'm here to assist you should you have any more questions or require further clarification.

**Comment by AIhasArrived** [comment]
Hello @baijuexzz  can i contact you to get help installng this locally ?
