### ISSUE TITLE
Get cuda error

### ISSUE THREAD

**Issue by zhangsanfeng86** [kenwaytis/faster-SadTalker-API#2]
Hi ,
Thank you for your great job.

When docker  compose up, get cuda error:
<img width="1426" alt="image" src="https://github.com/kenwaytis/faster-SadTalker-API/assets/73547638/c90e7266-1c71-4d50-b8ec-24a3a2ca4d0f">

**Comment by zhangsanfeng86** [comment]
-- docker exec -it sadtalker bash -c 'nvidia-smi'

Got:  bash: nvidia-smi: command not found

**Comment by AIhasArrived** [comment]
Hello @zhangsanfeng86  can i contact you to get help installng this locally ?
